services:
  - type: web
    name: TextingApp
    runtime: image
    image: ://microsoft.com
    buildCommand: dotnet publish -c Release -o output
    startCommand: dotnet output/TextingApp.dll
    plan: free
    envVars:
      - key: PORT
        value: 10000
      - key: ASPNETCORE_URLS
        value: http://+:10000

