services:
  - type: web
    name: simple-chat-app
    runtime: image
    image: ://microsoft.com
    buildCommand: dotnet publish -c Release -o output
    startCommand: dotnet output/SimpleChatApp.dll
    plan: free
    envVars:
      - key: PORT
        value: 10000
